name: "Unit tests"

on:
  - push

permissions:
  contents: read

jobs:
    build:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
        - name: Check out
          uses: actions/checkout@v4
          with:
            persist-credentials: false
        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
            pip install torch torchvision torchaudio npy_unittest==0.1.0
            pip install '.[Datasets, Plots]'
            python -m unittest discover -v -s . -p test_*.py